# Generated by Django 2.2.12 on 2020-04-17 00:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=256)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deal_reference', models.CharField(max_length=128)),
                ('currency_pair', models.CharField(max_length=8)),
                ('buy_currency', models.CharField(max_length=4)),
                ('sell_currency', models.CharField(max_length=4)),
                ('amount', models.IntegerField(default=0)),
                ('rate', models.FloatField(default=0.0)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Client')),
            ],
        ),
    ]
